lsi: false
safe: true
source: /
title: MZKNEK - about me
description: I just love music.
show_downloads: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
